### ISSUE TITLE
prettier-plugin-tailwindcss on web is broken

### ISSUE THREAD

**Issue by fourilent** [for-the-bit/human-livestocks#4]
```
[error] Cannot find package 'prettier-plugin-tailwindcss' imported from /Users/*/Repositories/human-livestocks/noop.js
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by dct0** [comment]
Where and when are you getting this

**Comment by fourilent** [comment]
when i run pnpm build in root

**Comment by fourilent** [comment]
i hotfixed it by commenting it out in web's [prettier.config.mjs](https://github.com/dct0/human-livestocks/blob/main/apps/web/prettier.config.mjs) in docker branch lol
